Add welcome text and menu buttons
saintprug/saintpruby_bot pull request #9
Opened 2019-05-05 14:38 UTC by k0va1

2019-05-05 20:25 UTC, IvanShamatov commented on dispatcher.rb
> +    elsif COMMANDS.include?(command)
Maybe it's better to make a similar interface with `dispatch_message`, but instead of having `COMMANDS` use `CALLBACK_COMMANDS` or just `CALLBACKS`

2019-05-05 20:31 UTC, IvanShamatov requested changes
Well, having welcome text is a really nice feature, which can introduce commands list to user. Though, having `Reply`-keyboard which is always open will duplicate functionality provided by @botfather by default.
having this interface
![image](https://user-images.githubusercontent.com/160239/57199857-bf791980-6f8c-11e9-9595-c4f22d5b619d.png)

instead of this one:
![image](https://user-images.githubusercontent.com/160239/57199877-f7805c80-6f8c-11e9-82cf-ebe3d32c839e.png)
Well, I don't know, I prefer built-in functionality

2019-05-05 21:29 UTC, k0va1 commented
Hm, I think it's better when user has and alternative. But for me commands keyboard is more convenient than always typing command itself.

2019-05-05 21:52 UTC, IvanShamatov commented
well you don't need to type, you just tap menu button `[ / ]` and it appears.

2019-05-06 08:02 UTC, IvanShamatov commented
How about splitting this PR into 2? one with `welcome text` and one will be omitted XD

2019-05-06 08:16 UTC, k0va1 commented
ok, sounds like a solution)

2019-05-07 12:40 UTC, k0va1 commented
@IvanShamatov i left only welcome message. Also i moved files with data to `data` folder

2019-05-07 13:13 UTC, merged